### PR TITLE
Added logging on generator

### LINKED ISSUE #55: OData-client-generation absorbs warnings from underlying generator
**Describe The Bug**

The CLI exposes the @sap/cloud-sdk-generator. However, if the could-sdk-generator would print a warning, this warning is not exposed to the end-user. I found two cases, where this happened:
- If the service path is not set in the .edmx file no warning is written. In this case the service-mapping.json in the input folder looks like
```json
{
  "RCMCandidate": {
    "directoryName": "sfo-data-service",
    "servicePath": "VALUE_IS_UNDEFINED",
    "npmPackageName": "sfo-data-service"
  }
}
```
A sample service to reproduce the issue is for example the [candidate service](https://api.sap.com/api/RCMCandidate/resource)
- If the --forceOverwrite option is not set but files are already present in the target directory also no warning is printed and silently nothing is done to the existing folder.

**To Reproduce**

1. Install the latest CLI 
2. Run the generator with one of the cases mentioned above
3. No warning is printed in the console

**Expected Behavior**

There should be the same warning exposed to the user as for the bare generator from @sap/cloud-sdk-generator. So that you know that files are not changed or the service path is not set.

**Used Versions:**

 - `node -v`:13.60
 - `npm -v`: 6.13.4
 - `sap-cloud-sdk -v`: 0.1.5

### PR DESCRIPTION
**Pull request by CharlesDuboisSAP**
## Proposed Changes

The generator logs it progress when typing:
```
generate-odata-client -i input -o output
```

But all logging was lost when typing:
```
sap-cloud-sdk generate-odata-client -i input -o output
```

So I piped the stdout of the generator command to the stdout of the CLI process

Closes #55"

## Checklist

- [ ] I have added or adjusted tests that prove my fix is effective or that my feature works
- [ ] I have added or adjusted documentation

### CODE REVIEW

**Comment by FrankEssenberger** [comment]
@CharlesDuboisSAP the next time you open a PR you can request me as reviewer. Then I get an email :-).

**Comment by FrankEssenberger** [comment]
@CharlesDuboisSAP the next time you open a PR you can request me as reviewer. Then I get an email :-). Or are you not allowed to do that?

**Comment by CharlesDuboisSAP** [comment]
> @CharlesDuboisSAP the next time you open a PR you can request me as reviewer. Then I get an email :-). Or are you not allowed to do that?

@FrankEssenberger I can put reviewers on this PR, will do next time!

**Comment by FrankEssenberger** [comment]
I checked and somehow not all content is shown. When I generate the test service via the cli I get: 

```
d068544@C02XC5CLJGH6 ~/W/cloud-sdk-charles (master)> node bin/run generate-odata-client -i test/resources/template-generator-odata-client/edmxSource -o generated/ --forceOverwrite
[2020-07-14T11:43:28.714Z] INFO     (generator-cli): Parsing args...
[2020-07-14T11:43:28.771Z] INFO     (generator): Generating entities for service: YY1_SOCIALNETWORKACCOUNT_CDS...
```

but when I install the generator from the SDK which the cli just wrappes I get more output for each file actually:
```
d068544@C02XC5CLJGH6 ~/W/cloud-sdk-charles (master)> node node_modules/@sap-cloud-sdk/generator/dist/generator-cli.js -i test/resources/template-generator-odata-client/edmxSource/ -o generated/ --force-overwrite
[2020-07-14T11:43:35.536Z] INFO     (generator-cli): Parsing args...
[2020-07-14T11:43:35.580Z] INFO     (generator): Generating entities for service: YY1_SOCIALNETWORKACCOUNT_CDS...
[2020-07-14T11:43:35.660Z] INFO     (generator): Generating entity: Yy1_Socialnetworkaccount...
[2020-07-14T11:43:35.717Z] INFO     (generator): Generating .npmrc for service: YY1_SOCIALNETWORKACCOUNT_CDS...
[2020-07-14T11:43:35.719Z] INFO     (generator): Generating typedoc.json for service: YY1_SOCIALNETWORKACCOUNT_CDS...
[2020-07-14T11:43:35.725Z] INFO     (generator): Starting to save files for project to disk. This can take a while...
[2020-07-14T11:43:35.727Z] INFO     (generator): Saving file: BatchRequest.ts...
[2020-07-14T11:43:37.401Z] INFO     (generator): Saving file: index.ts...
[2020-07-14T11:43:37.405Z] INFO     (generator): Saving file: Yy1_Socialnetworkaccount.ts...
[2020-07-14T11:43:37.490Z] INFO     (generator): Saving file: Yy1_SocialnetworkaccountRequestBuilder.ts...
[2020-07-14T11:43:37.526Z] INFO     (generator-cli): Generation of services finished successfully.
```

So I guess there is something not working with the piping of the complete content. Only parts are send.

**Comment by FrankEssenberger** [comment]
Also it would be good to have an assertion in one test to see if the content is there. Either add an assertion to an exising test or create a separate new one. There I would try to use a command which is quick so that we do not add a lot of extra time in the test process.

**Comment by CharlesDuboisSAP** [comment]
I don't really understand, it works for me
image
image
Altough maybe this is the issue?
image

**Comment by FrankEssenberger** [comment]
Works for me. Had a very old version of the sdk installed globally. Just a test needs to be added and also look if the `execa` is used perhaps somewhere else and the stdout is not piped.

**Comment by CharlesDuboisSAP** [comment]
execa wasn't used anywhere else and after more than 2 hours trying to trying to put 2 pipes for 2 writestreams, it is impossible, I don't think the pipe needs to be tested anyway.

**Comment by FrankEssenberger** [comment]
@CharlesDuboisSAP The test run locally just fine. As a final attempt I try to update the yarn.lock but I do not know why some tests are failliing in the pipeline.

**Comment by CharlesDuboisSAP** [comment]
@FrankEssenberger the tests are failing on my computer

**Comment by FrankEssenberger** [comment]
So I had now a few green runs. @CharlesDuboisSAP can you also pull the latest changes and try on your windows machine please.

**Comment by FrankEssenberger** [comment]
Every second build is green now. I really do not understand what is going on. The ubuntu is always green. But sometimes the mac or windows fail with some errors on npm i of the generator e2e test or so. We have to keep an eye on it.

**Pull request merged**
